### ISSUE TITLE
App insights not showing any logs post migration

### ISSUE THREAD

**Issue by ashkulkarni** [Azure-Samples/azure-cosmosdb-live-data-migrator#10]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>1. Deployed the migration app
2. Ran the migration tool for a collection and completed
3. Check app insights created for this migration tool
4. No logs were found in the app insights

### Any log messages given by the failure
> None

### Expected/desired behavior
> Logs of the migration tool being run

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> NA
<img width="547" alt="DevAppInsightsError" src="https://user-images.githubusercontent.com/7364660/81244864-62150f80-8fc8-11ea-8b00-cf757374dc8b.PNG">

### Mention any other details that might be useful
I also mentioned a new cosmos db and collection while installing the application but none of them got created in the resource group.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by FabianMeiswinkel** [comment]
This has been fixed in Version 2.0.0
