### ISSUE TITLE
Security Bug: Auto fill should be disabled for secrets

### ISSUE THREAD

**Issue by ashkulkarni** [Azure-Samples/azure-cosmosdb-live-data-migrator#11]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>1. The secret "Key" is exposed and poses a security risk as the auto-fill is enabled for this field

### Any log messages given by the failure
>

### Expected/desired behavior
> Fields which take secrets should disable the auto-fill on those fields.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
All

### Versions
> All

### Mention any other details that might be useful
As this is a critical migration tool it is likely to cause confusion or human error as some fields provide auto complete. I feel we should disable autofill for all the fields here.

**Comment by TheovanKraay** [comment]
Closing this as has been addressed in V2 of the app.
