### ISSUE TITLE
Reverse migration documentation

### ISSUE THREAD

**Issue by ashkulkarni** [Azure-Samples/azure-cosmosdb-live-data-migrator#12]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> We are trying to do a live migration and i do see there is a "Reverse Migration" button when the migration starts. But i do not see any documentation for this. 
 
Does it entail this - 
If there is an issue and we want to revert back to our old container. We do it on the client side and then also run this to migrate the changes from the new collection to the old ? 

### Any log messages given by the failure
> None

### Expected/desired behavior
> Documentation on revert and avoid data loss in this case

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

**Comment by TheovanKraay** [comment]
Closing this. App no longer has reverse migration feature in V2.
