### ISSUE TITLE
Reverse migration not working

### ISSUE THREAD

**Issue by ashkulkarni** [Azure-Samples/azure-cosmosdb-live-data-migrator#13]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>  
1. Try out a migration from Container A to Container B
2. Complete the migration 100% but not click on the "Complete migration" 
3. Update some records in the new container and insert new records in the new container
4. Try clicking on the Reverse migration to move the contents from Container B to Container A
5. The new element and updates will not be reflected in the Container A

### Any log messages given by the failure
> No logs

### Expected/desired behavior
> All the elements present in Container B should be reflected in Container A

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows

### Versions
> All

**Comment by TheovanKraay** [comment]
reverse migration feature removed from V2 version of app.
