### ISSUE TITLE
naming of parameter "cosmosdbaccount" mislead to fill account name instead URI. 

### ISSUE THREAD

**Issue by chshihMSFT** [Azure-Samples/azure-cosmosdb-live-data-migrator#16]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Expected/desired behavior
We (CSS) found the naming of parameter "cosmosdbaccount" might mislead users to fill account name instead URI. That caused the "client" Web App can't connect to metadata database and encounter error: _"The page cannot be displayed because an internal server error has occurred."_

To resolve this kind of issue, users can manually change to the correct URI in each App Service - Application Settings.
We can also add some descriptions into ARM template to prevent this happen again.

### Example:
```
    "cosmosdbaccount": {
      "type": "String"
	  , "defaultValue": "https://<account_name>.documents.azure.com:443/"
	  ,"metadata": {
            "description": "Cosmos DB account URI"
        }
    },
    "cosmosdbkey": {
      "type": "String"	  
	  , "defaultValue": "<account_key>"
	  ,"metadata": {
            "description": "Cosmos DB account read-write key"
        }
    },
    "cosmosdbdb": {
      "type": "String"
	  , "defaultValue": "migrationdb"
	  ,"metadata": {
            "description": "The database store migration metadata and state"
        }
    },
    "cosmosdbcollection": {
      "type": "String"
	  , "defaultValue": "migrationcollection"
	  ,"metadata": {
            "description": "The collection store migration metadata and state"
        }
    }
```

**Comment by dawwa** [comment]
thanks, I have been confused by the error for hours, and fortunately, I noticed this post 👍

**Comment by TheovanKraay** [comment]
closing this as V2 of the app does not require adding metedata or lease collection parameters.
