### ISSUE TITLE
Live migrator not working after the last checkin

### ISSUE THREAD

**Issue by ManishSC06** [Azure-Samples/azure-cosmosdb-live-data-migrator#24]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>specify source db details, target db details, and lease db details (not used optional field) after specifying the details click on start
   - No migration start for cosmosdb  and wait for 1 hrs
   - leasedb created in the target environment, its not take lease specified settings.
    I am also using the old migrator(setup 2 months back) it's working fine.

### Any log messages given by the failure
> no error is shown by after starting the migration, it will be on the same stage, just show source records count, target count always show 0 and no migration start

### Expected/desired behavior
>1. new leasedb created on the target database environment, it does not take the setting of specified settings of lease db
2. Migration did not start for the database

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
any version doesn't matter
### Versions
> not matter

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by UltraGC** [comment]
I have the same issue with the latest.

**Comment by TheovanKraay** [comment]
closing this as the root of this issue is described in issue 26 (leaving issue open it so it is clearer for other users).
