### ISSUE TITLE
Adding "/" at front of partition key causes a silent error

### ISSUE THREAD

**Issue by TheovanKraay** [Azure-Samples/azure-cosmosdb-live-data-migrator#26]
Adding "/" at front of partition key causes a silent error. For example, if the name of partition key is "PartitionKey" it should NOT be entered as "/PartitionKey" - application will crash with no warning as to what went wrong. However, this is misleading as the partition key for any given container displays in Cosmos DB portal as "/PartitionKey", so it is natural to enter this in the partition key fields for this app. 
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Adding the character "/" as front of partition key field name

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by FabianMeiswinkel** [comment]
This has been fixed in Version 2.0.1
