### ISSUE TITLE
Nothing shows up on the client url

### ISSUE THREAD

**Issue by lubyrex** [Azure-Samples/azure-cosmosdb-live-data-migrator#27]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
1. Creat a cosmosDB.
2. Press the "Deploy to Azure" button under the quick start section, and go through the steps. 
3. After deployment succeeded, visit client url
### Any log messages given by the failure
>
![image](https://user-images.githubusercontent.com/16534505/101466412-140c2400-397c-11eb-86aa-15daf8e650d5.png)

### Expected/desired behavior
>
Nothing shows up on the client url.
### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by lubyrex** [comment]
Sorry, I think I put in wrong values for the configs, but having some error messages would be nice!

**Comment by satheeshpayoda** [comment]
@lubyrex 
I'm also facing this error. Can you tell me how did you fix the issue? I'm not seeing any error in the Application Insight or Both Appservice logs?

**Comment by lubyrex** [comment]
@satheeshpayoda If you enable the log stream feature of the app service in Azure, you can see the application logs.

**Comment by satheeshpayoda** [comment]
@lubyrex 
Yes, I enabled Log Stream in the app service. But i didn't see any error logs.

Then i fixed this issue by removing cosmosdbcollection and cosmosdbdb in the Client AppService configuration and restarted the client app. Then it created a Metadata database by itself (migrationdetailsdb and migrationdetailscoll) and then i updated the same in the **both** app service configuration.
