### ISSUE TITLE
Migration stuck at around 20%

### ISSUE THREAD

**Issue by lubyrex** [Azure-Samples/azure-cosmosdb-live-data-migrator#28]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
I created a db account for metadata then used the same db account (with the same url) for my source, target and lease database, While doing the migration, I noticed that at first it moves data very quickly
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/16534505/101626383-dc72aa00-3a57-11eb-8b54-3472076fa737.png)
, but then gets stuck at 1/4 of the way
![image](https://user-images.githubusercontent.com/16534505/101626416-ebf1f300-3a57-11eb-80be-745a81b201ae.png)
now if I add some new data to my old db, the app still moves that new data to the new db and container
![image](https://user-images.githubusercontent.com/16534505/101626459-f9a77880-3a57-11eb-80ab-127570bede52.png)

### Any log messages given by the failure
>
None
### Expected/desired behavior
>
I expect the data count to be the same in source and destination db/container
### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by TheovanKraay** [comment]
Please try V2 of the migrator that has just been merged. This includes a number of improvements, including a bug fix for 429 errors (rate limiting) in target container, which may be a cause of your problem.

**Comment by lubyrex** [comment]
Wow thanks for the amazing update, will definitely give it a try. Quick question: does it support migrating multiple containers (ie. all containers in the entire db) at the same time?

**Comment by TheovanKraay** [comment]
yes just hit "create" for each one. But you would need to make sure you have enough app service instances if running a lot of container migrations in parallel. Let us know how you get on.

**Comment by lubyrex** [comment]
Hi I've just tried it, and it works perfectly! Thanks for the awesome tool! I tried using one instance to run the migration, and it still works fine on 4 containers. Does having multiple instances speed up the process?

**Comment by TheovanKraay** [comment]
Awesome, thanks for confirming. By default the app is deployed with 5 app service instances. You can scale this up and yes it can improve performance as long as you also have sufficient request units provisioned in the target containers. The effect of scaling up is that more physical partitions can be processed in parallel, since each instance will act as a change feed observer.
