### ISSUE TITLE
HTTP Error 500.30 - ANCM In-Process Start Failure

### ISSUE THREAD

**Issue by jbarguil** [Azure-Samples/azure-cosmosdb-live-data-migrator#30]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Follow the steps in Readme

### Any log messages given by the failure
> "HTTP Error 500.30 - ANCM In-Process Start Failure" when accessing the "-ui" after deployment

### Expected/desired behavior
> It should show the UI

### OS and Version?
> Hmm not sure?

### Versions
> 

### Mention any other details that might be useful

I followed the steps in the Readme and got to the point where it warned that "HTTP Error 500.30 - ANCM In-Process Start Failure" might happen - it did, and the suggested fix didn't solve it. Any ideas?

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jeremymaya** [comment]
I was able to solve the issue by updating the following values from the *Manifest* step to include the *Resouces Name Prefix*:

* `"logoutUrl"`
* `"replyUrlsWithType:url"`

For example, if I named the *Resource Name Prefix* as `livedatamigrator`, `logoutUrl` and `replyUrlsWithType:url` from *Manifest* should be the following:

```
"logoutUrl": "https://livedatamigrator-ui.azurewebsites.net/signout-callback-oidc",

"replyUrlsWithType": [
		{
			"url": "https://livedatamigrator-ui.azurewebsites.net/signin-oidc",
			"type": "Web"
		}
	],
```

I hope this helps 😵

**Comment by vtrphan** [comment]
i'm having this issue too, any the logoutUrl and replyUrlsWithType:url in the Manifest already contained the Resource Name Prefix. Hope someone can help
