### ISSUE TITLE
Data migration stuck at the same level on different migration attempts

### ISSUE THREAD

**Issue by frmedjo** [Azure-Samples/azure-cosmosdb-live-data-migrator#32]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I'm opening this issue on behalf of a customer. Customer migration gets stuck around 12.95% regardless of  targets. I found a similar [issue](https://github.com/Azure-Samples/azure-cosmosdb-live-data-migrator/issues/28) and the recommendation was to use V2 of the migrator which is what I believe the customer uses as he tried this tool just a few days go. Initially I thought it was because of some throttling on the CosmosDB end but customer tried the migration by creating a new target container with 30k  RU/s and the same behavior happened. He mentioned not stopping the migration and the tool stopped on its own. 

### Any log messages given by the failure
> See image below. Different targets, different days similar result.

**Container with 30k RU/s**

![image](https://user-images.githubusercontent.com/68447999/107089932-109ee880-67c5-11eb-8e17-8bf9d427277e.png)

**Container with 5100 RU/s**

![image](https://user-images.githubusercontent.com/68447999/107089942-15639c80-67c5-11eb-8987-8361e0466a20.png)

### Expected/desired behavior
> Migration to complete 100% with no failure

### OS and Version?
> Windows 10.

### Versions
> 

### Mention any other details that might be useful
Customer wants to create a synthetic partition key in the target container which I believe is possible and straightforward per the documentation

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by TheovanKraay** [comment]
A few questions:
Did customer share AppService logs?
What is the RU on source container?
Can you share the document structure?
What is the source partition key path, and what is the target partition key path?
Does the new partition key path/value exist in ALL documents in source container (seems there are over 400m)?

**Comment by FabianMeiswinkel** [comment]
My guess is this is due to failures migrating the documents. If storing the document in the target container fails for non-retriable reasons (invalid json, unique key constraint violation etc.) the document along with the error information is written to the Blob Storage account in the same resource group as the migration app. The name of the container is the id of the migration.

**Comment by TheovanKraay** [comment]
Some additional questions:

1. What is RU provisioned on source container?
2. Can you share doc structure?
3. What is the old partition key, and how is the new (synthetic) partition key mapped?
4. Are the values required for the new PK present in **all** the docs in source container (this could be a cause of failure)
5. As Fabian alluded to, did customer check the DLQ for poisoned docs? 
6. Can customer share appservice logs?

**Comment by TheovanKraay** [comment]
Hi @frmedjo, awaiting your comments to the above.

**Comment by frmedjo** [comment]
@TheovanKraay, I'm still awaiting updates from customer regarding your inquiries. I'll update you accordingly once I get more information.

**Comment by TheovanKraay** [comment]
@frmedjo did you get any response to this?

**Comment by frmedjo** [comment]
@TheovanKraay ,
yes this can be closed. I was on leave and you worked with Prashanth, Fabian and the customer offline to resolve this issue.
