### ISSUE TITLE
Having '/' in front of partition key causing migration job stuck at 0%.

### ISSUE THREAD

**Issue by MikeYuMsft** [Azure-Samples/azure-cosmosdb-live-data-migrator#39]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Run a migration with a `/` in front of partition key with target container not exist yet(I'm running on a new cosmos db). 
 The job will show 0 migrated and stuck there. 

### Any log messages given by the failure
>

### Expected/desired behavior
> If we don't need to add `/` in front of partition key, it would be nice to have it show in the UI to remind users or the documentation. 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
> Windows 10
### Versions
> Latest. 

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Radamonas** [comment]
Noticed this issue as well and it seems quite strange as / is mandatory almost everywhere the partition key is asked.
