### ISSUE TITLE
Partition key datatype being changed to string

### ISSUE THREAD

**Issue by siddhantchawla** [Azure-Samples/azure-cosmosdb-live-data-migrator#44]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> On migrating a container having partition key datatype as long int, the documents in the destination container have the same value of the partition key converted to string.

### Expected/desired behavior
> The partition key datatype should not change.

**Comment by ethanturk** [comment]
I'm currently fighting through the fall out of this bug, as well.
