### ISSUE TITLE
Total And Migrated Count are both 0 (even if db contains data)

### ISSUE THREAD

**Issue by csesek** [Azure-Samples/azure-cosmosdb-live-data-migrator#45]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Install the tool in azure
Access the URL
Enter details and start migration
Total and Migrated column shows 0, even when db contains data.

### Any log messages given by the failure
> Couldn't find logs

### Expected/desired behavior
> Error logs or alerts to know if any configuration issue persists

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Its created by default. No additional changes made

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by csesek** [comment]
This is the current state.

<img width="1369" alt="Screenshot 2022-01-22 at 12 32 54 AM" src="https://user-images.githubusercontent.com/16016671/150585204-6fe268e1-9557-4a6b-ae14-5f29652fc366.png">

**Comment by NANDAKISHORE92** [comment]
@csesek Make sure you add the connection strings in the key vault for the source and the target databases. Meanwhile you can also check the logs in the Application insights attached to this live migrator web app.
