### ISSUE TITLE
Errors deploying resources type of "Microsoft.Web/sites/extensions"

### ISSUE THREAD

**Issue by osharena** [Azure-Samples/azure-cosmosdb-live-data-migrator#57]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> following the main guide "READ.md" in https://github.com/Azure-Samples/azure-cosmosdb-live-data-migrator

### Any log messages given by the failure
>failed to deploy

### Expected/desired behavior
>success to deploy

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

I'm trying to deploy my app following the guide of [https://github.com/Azure-Samples/azure-cosmosdb-live-data-migrator].
I'm just following the guide totally the same way except just unique values like app name.

Like the picture, there are errors deploying and all the three errors are for Type of "Microsoft.Web/sites/extensions".
When I clicked "Operation details" to check error occurred deploying for example "kjnoh-migration-test-executorjob/MSDeploy", it just shows 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
{
    "status": "failed",
    "error": {
        "code": "Failed",
        "message": "Failed to download package.\r\nARM-MSDeploy Deploy Failed: 'System.AggregateException: One or more errors occurred. ---&gt; System.Net.WebException: The remote server returned an error: (409) Conflict.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\r\n   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__17.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__15.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadPackageAndSettings&gt;d__27.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadAndDeployPackage&gt;d__25.MoveNext()\r\n---&gt; (Inner Exception #0) System.Net.WebException: The remote server returned an error: (409) Conflict.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)&lt;---\r\n'"
    }
}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
but I have no idea what the error message means.
The same errors are always happen even though I try it again and again even changing unique names that I have to enter making the app. And "Redeploy" doesn't work either.

Could you teach me what things possibly make the errors?

<img src="https://webhook-kj-noh.spl.link/error.PNG">

**Comment by Marko-TRG** [comment]
I have the same problem. Looks like this code is not being actively maintained. According to [this PR](https://github.com/Azure-Samples/azure-cosmosdb-live-data-migrator/pull/42/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) , one must create publicly available storage, create the packages locally from source, upload to storage and then use those URLs instead.

**Comment by PaulCardus** [comment]
does anyone have a url for the packages as I can't seem to publish these in visual studio

**Comment by Marko-TRG** [comment]
You don't need to publish them using VS. Just zip the folders as per the instructions and upload to any public web server, e.g. Azure Blob storage, which lets you upload using a web interface. In this example, I have created a container called cosmos-migrator with public access type 'Blob'.

![image](https://user-images.githubusercontent.com/65399316/219352341-83d7440c-c2f8-436f-98ae-03e8334668ed.png)
